export function getRandomNumber(max){
    return Math.floor(Math.random() * max)
}

export const frasesBiscoitoDaSorte = [
    "A vida é uma jornada, não um destino final.",
    "Grandes oportunidades surgem quando você menos espera.",
    "A persistência é o caminho do êxito.",
    "Acredite nos seus sonhos e lute por eles.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Seja a mudança que você deseja ver no mundo.",
    "Sorria, você está no controle da sua própria felicidade.",
    "A gratidão transforma o que temos em suficiente.",
    "O segredo da felicidade está em encontrar alegria nas pequenas coisas da vida.",
    "O importante não é vencer todos os dias, mas lutar sempre.",
    "Tudo é possível quando você acredita em si mesmo.",
    "Nunca é tarde demais para ser quem você quer ser.",
    "A sorte favorece a mente preparada.",
    "A melhor maneira de prever o futuro é criá-lo.",
    "O que quer que você decida fazer, faça com todo o seu coração.",
    "A felicidade não é algo pronto. Ela é feita de suas próprias ações.",
    "Cada dia é uma oportunidade para ser uma versão melhor de si mesmo.",
    "Seja gentil, pois cada pessoa que você encontra está travando uma batalha que você não sabe nada a respeito.",
    "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.",
    "Não importa o quão devagar você vá, desde que você não pare.",
    "A paciência é amarga, mas seus frutos são doces.",
    "O destino não é uma questão de chance, é uma questão de escolha.",
    "O que você faz hoje pode melhorar todos os seus amanhãs.",
    "Quanto mais você trabalha, mais sorte você tem.",
    "A persistência é o segredo do sucesso.",
    "Grandes realizações não vêm de uma única grande chance, mas de muitas pequenas oportunidades aproveitadas ao longo do tempo.",
    "Acredite que você pode e você já está no meio do caminho.",
    "Um sorriso é a chave mágica que abre o coração de todos.",
    "Cada momento é uma oportunidade para fazer uma nova escolha.",
    "Aprenda com ontem, viva para hoje, tenha esperança para amanhã.",
    "Se você quer ser feliz, seja.",
    "O tempo é o melhor autor. Sempre encontra um final perfeito.",
    "A felicidade não é algo que se adia para o futuro, é algo que você projeta para o presente.",
    "A vida é como andar de bicicleta. Para manter o equilíbrio, você precisa se manter em movimento.",
    "Se você não pode fazer grandes coisas, faça pequenas coisas de maneira grandiosa.",
    "A verdadeira felicidade está em aproveitar as pequenas coisas da vida.",
    "Você é mais forte do que pensa e mais capaz do que imagina.",
    "Nada é permanente neste mundo cruel. Nem mesmo os nossos problemas.",
    "O otimismo é a fé em ação. Nada pode ser feito sem esperança e confiança.",
    "A beleza está nos olhos de quem vê, mas a felicidade está no coração de quem sente.",
    "O sucesso não é a chave para a felicidade. A felicidade é a chave para o sucesso. Se você ama o que faz, você terá sucesso.",
    "A vida é uma aventura ousada ou não é nada.",
    "A vida é feita de escolhas. Escolha ser feliz.",
    "Não é o que você olha que importa, é o que você vê.",
    "A verdadeira sorte consiste em estar pronto para as oportunidades que surgem.",
    "Você é mais corajoso do que acredita, mais forte do que parece e mais inteligente do que pensa.",
    "Acredite nos seus sonhos e eles se tornarão realidade.",
    "O primeiro passo para o sucesso é acreditar que você pode.",
    "Cada dia é uma nova chance de ser melhor que ontem.",
    "Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados.",
    "Não deixe o medo decidir o que você faz.",
    "Se você quer algo que nunca teve, precisa fazer algo que nunca fez.",
    "O que você pensa, você se torna. O que você sente, você atrai. O que você imagina, você cria.",
  ];